=== easyguyme/Company-Project/document/api/schemas/management/channel/edit-wechat-payment/post/schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "type": "object",
  "properties": {
    "appId": {
      "type": "string",
      "required": true,
      "description": "渠道appId"
    },
    "sellerId": {
      "type": "string",
      "required": true,
      "description": "微信商户ID / 卖家支付宝账户号"
    },
    "apiKey": {
      "type": "string",
      "required": true,
      "description": "API安全密钥"
    },
    "p12CredentialId": {
      "type": "string",
      "required": false,
      "description": "证书文件的ID, 修改时, 如果传回原ID说明当前文件没有改变"
    },
    "p12Credential": {
      "type": "file",
      "required": false,
      "description": "pkcs12格式"
    },
    "pemCredentialId": {
      "type": "string",
      "required": false,
      "description": "证书文件的ID, 修改时, 如果传回原ID说明当前文件没有改变"
    },
    "pemCredential": {
      "type": "file",
      "required": false,
      "description": "证书pem格式"
    },
    "pemCredentialKeyId": {
      "type": "string",
      "required": false,
      "description": "证书文件的ID, 修改时, 如果传回原ID说明当前文件没有改变"
    },
    "pemCredentialKey": {
      "type": "file",
      "required": false,
      "description": "证书密钥pem格式"
    },
    "caCredentialId": {
      "type": "string",
      "required": false,
      "description": "证书文件的ID, 修改时, 如果传回原ID说明当前文件没有改变"
    },
    "caCredential": {
      "type": "file",
      "required": false,
      "description": "CA证书"
    }
  }
}

=== easyguyme/Company-Project/document/api/examples/management/channel/edit-wechat-payment/post/request.json
{
    "appId":"2014102700014769",
    "sellerId":"10010000",
    "apiKey":"20141027014769",
    "p12CredentialId":"20141027014769",
    "p12Credential":"apiclient_cert.p12",
    "pemCredentialId":"20141027014769",
    "pemCredential":"apiclient_cert.pem",
    "pemCredentialKey":"apiclient_key.pem",
    "pemCredentialKeyId":"20141027014769",
    "caCredentialId":"20141027014769",
    "caCredential":"rootca.pem"
}
